CREATE TABLE CAMERA(
CAMERA_NUM NUMBER(5) PRIMARY KEY,
CAMERA_STORENAME VARCHAR2(50) NOT NULL,
CAMERA_TOTAL NUMBER(7) NOT NULL,
CAMERA_DATE DATE NOT NULL,
USER_ID VARCHAR2(15) NOT NULL,
ORIGINAL_FILEPATH	VARCHAR2(100),
RENAME_FILEPATH	VARCHAR2(100),
CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES MEMBER(USERID)
);


INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 10000, SYSDATE, 'admin' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 20000, SYSDATE, 'user01' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 24000, '2022-02-06', 'admin' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 30000, '2022-02-07', 'admin' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 50000, '2022-02-15', 'user01' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user02' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user02' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 30000, '2022-02-01', 'user02' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 20000, '2022-02-07', 'user02' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-01', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-11', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-10', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-09', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-08', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-07', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 50000, '2022-02-06', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-02-05', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 30000, '2022-02-04', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 10000, '2022-02-03', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 20000, '2022-02-02', 'user01' );
commit;

CREATE SEQUENCE SEQ_PID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000
NOCYCLE
NOCACHE
NOORDER;

CREATE TABLE PRODUCT(
PRODUCT_NUM NUMBER(7) PRIMARY KEY,
CAMERA_NUM NUMBER(5) NOT NULL,
CONSTRAINT FK_CAMERA FOREIGN KEY(CAMERA_NUM) REFERENCES CAMERA(CAMERA_NUM),
ITEM VARCHAR2(150),
QUANTITY NUMBER(4) NOT NULL,
UNIT_PRICE NUMBER(7) NOT NULL,
PRICE NUMBER(8) NOT NULL
);

INSERT INTO PRODUCT(PRODUCT_NUM, CAMERA_NUM, ITEM, QUANTITY, UNIT_PRICE, PRICE)
VALUES(SEQ_PID.nextval, 8, '¾¾±×·¥', 2, 500, 1000 );
INSERT INTO PRODUCT(PRODUCT_NUM, CAMERA_NUM, ITEM, QUANTITY, UNIT_PRICE, PRICE)
VALUES(SEQ_PID.nextval, 8, '»õÄÞ´ÞÄÞ', 1, 500, 500 );
INSERT INTO PRODUCT(PRODUCT_NUM, CAMERA_NUM, ITEM, QUANTITY, UNIT_PRICE, PRICE)
VALUES(SEQ_PID.nextval, 8, '²¿ºÏÄ¨ÀÎÀý¹Ì¸À', 1, 1500, 1500 );
INSERT INTO PRODUCT(PRODUCT_NUM, CAMERA_NUM, ITEM, QUANTITY, UNIT_PRICE, PRICE)
VALUES(SEQ_PID.nextval, 8, 'ÂüÀÌ½½', 2, 2100, 4200 );
INSERT INTO PRODUCT(PRODUCT_NUM, CAMERA_NUM, ITEM, QUANTITY, UNIT_PRICE, PRICE)
VALUES(SEQ_PID.nextval, 8, 'ºÒ´ßººÀ½¸é', 2, 1500, 3000 );
commit;
